"""Add templates table

Revision ID: 042dbd919452
Revises: 69d16f31da52
Create Date: 2026-02-12 17:47:05.122471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '042dbd919452'
down_revision: Union[str, Sequence[str], None] = '69d16f31da52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('structure_hash', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('variables_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('cluster_source_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_templates_structure_hash'), 'templates', ['structure_hash'], unique=False)
    op.create_index(op.f('ix_templates_tenant_id'), 'templates', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_tenant_id'), table_name='templates')
    op.drop_index(op.f('ix_templates_structure_hash'), table_name='templates')
    op.drop_table('templates')
    # ### end Alembic commands ###
