"""add_zone_mappings_table

Revision ID: 11af202ecae3
Revises: f8ceb4547883
Create Date: 2026-02-12 22:16:59.131399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '11af202ecae3'
down_revision: Union[str, Sequence[str], None] = 'f8ceb4547883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zone_mappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('zone_id', sa.String(), nullable=False),
    sa.Column('position_stats', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('origin', sa.Enum('AUTO', 'HUMAN', name='mappingorigin'), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['template_id'], ['templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('template_id')
    )
    op.create_index(op.f('ix_zone_mappings_tenant_id'), 'zone_mappings', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_zone_mappings_tenant_id'), table_name='zone_mappings')
    op.drop_table('zone_mappings')
    # ### end Alembic commands ###
