"""add_table_templates_and_ooxml_path

Revision ID: 370d79bd5bfd
Revises: b670fca4bc0b
Create Date: 2026-02-13 09:54:52.998450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '370d79bd5bfd'
down_revision: Union[str, Sequence[str], None] = 'b670fca4bc0b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('table_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('storage_path', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_table_templates_tenant_id'), 'table_templates', ['tenant_id'], unique=False)
    op.add_column('skeletons', sa.Column('ooxml_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skeletons', 'ooxml_path')
    op.drop_index(op.f('ix_table_templates_tenant_id'), table_name='table_templates')
    op.drop_table('table_templates')
    # ### end Alembic commands ###
