"""add_label_catalog_and_user_label

Revision ID: 63ac525c241b
Revises: 11af202ecae3
Create Date: 2026-02-12 22:26:54.098883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63ac525c241b'
down_revision: Union[str, Sequence[str], None] = '11af202ecae3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('label_catalog',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('entity_type', sa.Enum('TEMPLATE', 'ASSET', name='entitytype'), nullable=False),
    sa.Column('entity_hash', sa.String(), nullable=False),
    sa.Column('label_name', sa.String(), nullable=False),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'entity_hash', 'entity_type', name='uq_tenant_hash_type')
    )
    op.create_index(op.f('ix_label_catalog_entity_hash'), 'label_catalog', ['entity_hash'], unique=False)
    op.create_index(op.f('ix_label_catalog_tenant_id'), 'label_catalog', ['tenant_id'], unique=False)
    op.add_column('templates', sa.Column('user_label', sa.String(), nullable=True))
    op.create_index(op.f('ix_templates_user_label'), 'templates', ['user_label'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_templates_user_label'), table_name='templates')
    op.drop_column('templates', 'user_label')
    op.drop_index(op.f('ix_label_catalog_tenant_id'), table_name='label_catalog')
    op.drop_index(op.f('ix_label_catalog_entity_hash'), table_name='label_catalog')
    op.drop_table('label_catalog')
    # ### end Alembic commands ###
