"""add_synced_at_to_zone_mappings

Revision ID: a5b234b6e461
Revises: 370d79bd5bfd
Create Date: 2026-02-13 10:03:53.694845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5b234b6e461'
down_revision: Union[str, Sequence[str], None] = '370d79bd5bfd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('zone_mappings', sa.Column('synced_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('zone_mappings', 'synced_at')
    # ### end Alembic commands ###
