"""add_preview_text_to_templates

Revision ID: b670fca4bc0b
Revises: 63ac525c241b
Create Date: 2026-02-13 06:46:42.507448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b670fca4bc0b'
down_revision: Union[str, Sequence[str], None] = '63ac525c241b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('preview_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'preview_text')
    # ### end Alembic commands ###
