"""add_seed_tracking_to_template

Revision ID: c362fa140686
Revises: f1783a340825
Create Date: 2026-02-12 19:18:50.025134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c362fa140686'
down_revision: Union[str, Sequence[str], None] = 'f1783a340825'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_seed', sa.Boolean(), nullable=True))
    op.add_column('templates', sa.Column('seed_label', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'seed_label')
    op.drop_column('templates', 'is_seed')
    # ### end Alembic commands ###
