"""add_seed_anchors_table

Revision ID: e3c148797131
Revises: c362fa140686
Create Date: 2026-02-12 21:50:23.726379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e3c148797131'
down_revision: Union[str, Sequence[str], None] = 'c362fa140686'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_anchors',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(), nullable=False),
    sa.Column('text', sa.String(), nullable=False),
    sa.Column('vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_seed_anchors_tenant_id'), 'seed_anchors', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_seed_anchors_tenant_id'), table_name='seed_anchors')
    op.drop_table('seed_anchors')
    # ### end Alembic commands ###
