"""add_s3_version_id_to_skeletons

Revision ID: e4f4238378b5
Revises: a5b234b6e461
Create Date: 2026-02-13 10:25:46.942780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4f4238378b5'
down_revision: Union[str, Sequence[str], None] = 'a5b234b6e461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skeletons', sa.Column('s3_version_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skeletons', 's3_version_id')
    # ### end Alembic commands ###
