"""Add is_boilerplate column to templates

Revision ID: f1783a340825
Revises: 042dbd919452
Create Date: 2026-02-12 18:03:19.688814

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f1783a340825'
down_revision: Union[str, Sequence[str], None] = '042dbd919452'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('is_boilerplate', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'is_boilerplate')
    # ### end Alembic commands ###
